# ZerodhaWise Configuration File
# Copy this file to config.yaml and update with your credentials

# Zerodha API Configuration
zerodha:
  api_key: "aqnhrjdciu1f4oe0"
  api_secret: "yhgv0jniafkz61umy87kfvcb1kwne5bx"
  access_token: "your_access_token_here"  # Optional, will be generated if not provided

# Database Configuration
database:
  url: "sqlite:///portfolio.db"  # SQLite database (default)
  # For PostgreSQL: "postgresql://username:password@localhost:5432/zerodhawise"
  # For MySQL: "mysql://username:password@localhost:3306/zerodhawise"

# Logging Configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR, CRITICAL
  file: "logs/zerodhawise.log"

# Data Storage Configuration
data:
  backup_enabled: true
  backup_interval_days: 7
  max_data_age_days: 365  # Keep data for 1 year

# Chart and Report Configuration
reports:
  output_directory: "reports"
  chart_format: "png"  # png, pdf, svg
  interactive_dashboard: true
  auto_generate_reports: true

# Performance Analysis Configuration
performance:
  risk_free_rate: 0.02  # 2% annual risk-free rate
  benchmark_symbol: "NIFTY50"  # Benchmark for comparison
  rolling_window_days: 30

# Risk Analysis Configuration
risk:
  var_confidence_level: 0.95  # 95% VaR
  max_drawdown_threshold: 0.20  # 20% max drawdown threshold
  concentration_threshold: 0.70  # 70% concentration threshold

# Notification Configuration (Future Feature)
notifications:
  email_enabled: false
  email_smtp_server: "smtp.gmail.com"
  email_smtp_port: 587
  email_username: "your_email@gmail.com"
  email_password: "your_app_password"
  alert_thresholds:
    portfolio_loss: 0.05  # 5% loss alert
    single_stock_loss: 0.10  # 10% single stock loss alert 